name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v3      

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '${{ matrix.java }}'

      - name: Test
        run: sbt test scripted

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '11'
      - run: git fetch --unshallow
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
